version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: innovatech_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: api-ventas
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=admin123
    depends_on:
      - db

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: api-despachos
    ports:
      - "8081:8081"
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=innovatech_db
      - DB_USERNAME=root
      - DB_PASSWORD=admin123
    depends_on:
      - db

  frontend:
    build:
      context: ./front_despacho
    container_name: web-frontend
    ports:
      - "80:80"
    depends_on:
      - backend-ventas
      - backend-despachos

volumes:
  dbdata: