name: CI/CD Innovatech Deployment

on:
  push:
    branches: [ "deploy" ]

jobs:
  # ETAPA 1: Compilar y subir imágenes a AWS ECR
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Backend Ventas
      run: |
        docker build -t 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:latest ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:latest

    - name: Build and Push Backend Despachos
      run: |
        docker build -t 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest

    - name: Build and Push Frontend
      run: |
        docker build -t 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest ./front_despacho
        docker push 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest

  # ETAPA 2: Despliegue en Amazon EKS
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Update KubeConfig
      # Reemplaza 'innovatech-eks' por el nombre exacto de tu clúster si es diferente
      run: aws eks update-kubeconfig --region us-east-1 --name innovatech-eks 

    - name: Restart Deployments in EKS
      # Esto obliga a Kubernetes a descargar la imagen ":latest" que acabas de subir en la Etapa 1
      run: |
        kubectl rollout restart deployment api-ventas -n innovatech
        kubectl rollout restart deployment api-despachos -n innovatech
        kubectl rollout restart deployment web-frontend -n innovatech
