name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
      - master # Se ejecutará cuando hagas push a 'main' o 'master'

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: devOps-eks
  AWS_ACCOUNT_ID: "476752693395"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construir y subir Backend Ventas
      run: |
        cd back-Ventas_SpringBoot/Springboot-API-REST
        docker build -t tienda-backend-ventas .
        docker tag tienda-backend-ventas:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend-ventas:eks-v1
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend-ventas:eks-v1

    - name: Construir y subir Backend Despachos
      run: |
        cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker build -t tienda-backend-despachos .
        docker tag tienda-backend-despachos:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend-despachos:eks-v1
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-backend-despachos:eks-v1

    - name: Construir y subir Frontend
      run: |
        cd front_despacho
        docker build -t tienda-frontend .
        docker tag tienda-frontend:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-frontend:eks-v1
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tienda-frontend:eks-v1

    - name: Configurar kubectl (kubeconfig)
      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Desplegar todos los manifiestos (Deployment, Service, HPA)
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -n tienda -f k8s/